# Classifying Penguins with Keras

In [2]:
import sys
!{sys.executable} -m pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp312-cp312-win_amd64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in C:\Users\2003n\AppData\Roaming\Python\Python312\site-packages (from tensorflow) (25.0)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in C:\Users\2003n\AppData\Roaming\Python\Python312\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from tensorflow) (2.1.2)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.80.0-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.14.1-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from tensorflow) (2.3.4)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp312-cp312-win_amd64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.4-cp312-cp312-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.10.5)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.47.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: rich in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Collecting namex (from keras>=3.12.0->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Downloading optree-0.19.1-cp312-cp312-win_amd64.whl.metadata (32 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\2003n\AppData\Roaming\Python\Python312\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Downloading tensorflow-2.21.0-cp312-cp312-win_amd64.whl (350.9 MB)
   ---------------------------------------- 0.0/350.9 MB ? eta -:--:--
   ---------------------------------------- 2.6/350.9 MB 16.7 MB/s eta 0:00:21
   - -------------------------------------- 11.0/350.9 MB 32.8 MB/s eta 0:00:11
   -- ------------------------------------- 18.9/350.9 MB 34.0 MB/s eta 0:00:10
   -- ------------------------------------- 23.9/350.9 MB 32.1 MB/s eta 0:00:11
   --- ------------------------------------ 30.1/350.9 MB 31.4 MB/s eta 0:00:11
   ---- ----------------------------------- 41.9/350.9 MB 35.6 MB/s eta 0:00:09
   ----- ---------------------------------- 50.6/350.9 MB 36.6 MB/s eta 0:00:09
   ------- -------------------------------- 61.6/350.9 MB 38.5 MB/s eta 0:00:08
   -------- ------------------------------- 70.3/350.9 MB 38.9 MB/s eta 0:00:08
   -------- ------------------------------- 78.6/350.9 MB 38.9 MB/s eta 0:00:08
   ---------- ----------------------------- 91.2/350.9 MB 40.7 MB/s eta 0:00:07
   ----------- --------------------------- 102.8/350.9 MB 42.0 MB/s eta 0:00:06
   ------------- ------------------------- 119.3/350.9 MB 44.8 MB/s eta 0:00:06
   -------------- ------------------------ 133.2/350.9 MB 46.7 MB/s eta 0:00:05
   ---------------- ---------------------- 148.1/350.9 MB 48.3 MB/s eta 0:00:05
   ----------------- --------------------- 159.9/350.9 MB 48.7 MB/s eta 0:00:04
   ------------------ -------------------- 169.1/350.9 MB 48.7 MB/s eta 0:00:04
   -------------------- ------------------ 187.2/350.9 MB 50.7 MB/s eta 0:00:04
   ---------------------- ---------------- 200.8/350.9 MB 51.5 MB/s eta 0:00:03
   ----------------------- --------------- 213.9/350.9 MB 52.2 MB/s eta 0:00:03
   ------------------------- ------------- 229.1/350.9 MB 53.1 MB/s eta 0:00:03
   --------------------------- ----------- 246.2/350.9 MB 54.4 MB/s eta 0:00:02
   ----------------------------- --------- 261.1/350.9 MB 55.3 MB/s eta 0:00:02
   ------------------------------ -------- 278.4/350.9 MB 58.8 MB/s eta 0:00:02
   -------------------------------- ------ 295.7/350.9 MB 64.2 MB/s eta 0:00:01
   ---------------------------------- ---- 310.9/350.9 MB 65.7 MB/s eta 0:00:01
   ------------------------------------ -- 325.6/350.9 MB 67.3 MB/s eta 0:00:01
   --------------------------------------  345.2/350.9 MB 72.9 MB/s eta 0:00:01
   --------------------------------------  350.7/350.9 MB 73.5 MB/s eta 0:00:01
   --------------------------------------  350.7/350.9 MB 73.5 MB/s eta 0:00:01
   ---------------------------------------- 350.9/350.9 MB 65.2 MB/s  0:00:06
Downloading grpcio-1.80.0-cp312-cp312-win_amd64.whl (4.9 MB)
   ---------------------------------------- 0.0/4.9 MB ? eta -:--:--
   ---------------------------------------- 4.9/4.9 MB 73.3 MB/s  0:00:00
Downloading h5py-3.14.0-cp312-cp312-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
   ---------------------------------------- 2.9/2.9 MB 12.7 MB/s  0:00:00
Downloading ml_dtypes-0.5.4-cp312-cp312-win_amd64.whl (212 kB)
Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl (437 kB)
Downloading absl_py-2.4.0-py3-none-any.whl (135 kB)
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading wheel-0.47.0-py3-none-any.whl (32 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading gast-0.7.0-py3-none-any.whl (22 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading keras-3.14.1-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 1.6/1.6 MB 44.1 MB/s  0:00:00
Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl (26.4 MB)
   ---------------------------------------- 0.0/26.4 MB ? eta -:--:--
   ----------------- ---------------------- 11.3/26.4 MB 54.2 MB/s eta 0:00:01
   ---------------------------------------  26.2/26.4 MB 66.5 MB/s eta 0:00:01
   ---------------------------------------- 26.4/26.4 MB 57.7 MB/s  0:00:00
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.19.1-cp312-cp312-win_amd64.whl (341 kB)
Installing collected packages: namex, libclang, flatbuffers, wheel, termcolor, protobuf, optree, opt_einsum, ml_dtypes, h5py, grpcio, google_pasta, gast, absl-py, astunparse, keras, tensorflow

   -- -------------------------------------  1/17 [libclang]
   -- -------------------------------------  1/17 [libclang]
   -- -------------------------------------  1/17 [libclang]
   ---- -----------------------------------  2/17 [flatbuffers]
   ------- --------------------------------  3/17 [wheel]
   ------- --------------------------------  3/17 [wheel]
   ------- --------------------------------  3/17 [wheel]
   --------- ------------------------------  4/17 [termcolor]
   ----------- ----------------------------  5/17 [protobuf]
   ----------- ----------------------------  5/17 [protobuf]
   ----------- ----------------------------  5/17 [protobuf]
   ----------- ----------------------------  5/17 [protobuf]
   ----------- ----------------------------  5/17 [protobuf]
   ----------- ----------------------------  5/17 [protobuf]
   ----------- ----------------------------  5/17 [protobuf]
   ----------- ----------------------------  5/17 [protobuf]
   ----------- ----------------------------  5/17 [protobuf]
   -------------- -------------------------  6/17 [optree]
   -------------- -------------------------  6/17 [optree]
   -------------- -------------------------  6/17 [optree]
   ---------------- -----------------------  7/17 [opt_einsum]
   ---------------- -----------------------  7/17 [opt_einsum]
   ---------------- -----------------------  7/17 [opt_einsum]
   ---------------- -----------------------  7/17 [opt_einsum]
   ---------------- -----------------------  7/17 [opt_einsum]
   --------------------- ------------------  9/17 [h5py]
   --------------------- ------------------  9/17 [h5py]
   --------------------- ------------------  9/17 [h5py]
   --------------------- ------------------  9/17 [h5py]
   --------------------- ------------------  9/17 [h5py]
   --------------------- ------------------  9/17 [h5py]
   --------------------- ------------------  9/17 [h5py]
   --------------------- ------------------  9/17 [h5py]
   --------------------- ------------------  9/17 [h5py]
   --------------------- ------------------  9/17 [h5py]
   ----------------------- ---------------- 10/17 [grpcio]
   ----------------------- ---------------- 10/17 [grpcio]
   ----------------------- ---------------- 10/17 [grpcio]
   ----------------------- ---------------- 10/17 [grpcio]
   ----------------------- ---------------- 10/17 [grpcio]
   ----------------------- ---------------- 10/17 [grpcio]
   ----------------------- ---------------- 10/17 [grpcio]
   ----------------------- ---------------- 10/17 [grpcio]
   ------------------------- -------------- 11/17 [google_pasta]
   ------------------------- -------------- 11/17 [google_pasta]
   ------------------------- -------------- 11/17 [google_pasta]
   ------------------------- -------------- 11/17 [google_pasta]
   ---------------------------- ----------- 12/17 [gast]
   ------------------------------ --------- 13/17 [absl-py]
   ------------------------------ --------- 13/17 [absl-py]
   ------------------------------ --------- 13/17 [absl-py]
   ------------------------------ --------- 13/17 [absl-py]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ----------------------------------- ---- 15/17 [keras]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]
   ------------------------------------- -- 16/17 [tensorflow]

  WARNING: The script wheel.exe is installed in 'c:\Users\2003n\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts saved_model_cli.exe, tf_upgrade_v2.exe, tflite_convert.exe and toco.exe are installed in 'c:\Users\2003n\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [7]:
import sys
!{sys.executable} -m pip install palmerpenguins

Collecting palmerpenguins
  Downloading palmerpenguins-0.1.6-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: pandas in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from palmerpenguins) (2.3.3)
Requirement already satisfied: numpy in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from palmerpenguins) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\2003n\AppData\Roaming\Python\Python312\site-packages (from pandas->palmerpenguins) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas->palmerpenguins) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas->palmerpenguins) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\2003n\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas->palmerpenguins) (1.17.0)
Downloading palmerpenguins-0.1.6-py3-none-any.whl (18 kB)
Installing collected packages: palmerpenguins
Successfully installed palmerpenguins-0.1.6

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [20]:
penguins = penguins.dropna()
penguins.shape

(333, 8)

In [21]:
penguins = penguins.sample(frac=1, random_state = 42).reset_index(drop=True)

In [22]:
penguins_x = pd.concat([penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,3250.0,39.5,16.7,178.0,True,False
1,3675.0,50.9,17.9,196.0,True,False
2,4000.0,42.1,19.1,195.0,False,True
3,4850.0,46.6,14.2,210.0,True,False
4,4050.0,41.1,18.2,192.0,False,True
...,...,...,...,...,...,...
328,4750.0,49.6,15.0,216.0,False,True
329,3900.0,37.2,19.4,184.0,False,True
330,3200.0,39.7,17.7,193.0,True,False
331,3950.0,45.2,17.8,198.0,True,False
332,3175.0,38.1,17.0,181.0,True,False

In [23]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,0.152778,0.269091,0.428571,0.101695,1.0,0.0
1,0.270833,0.683636,0.571429,0.406780,1.0,0.0
2,0.361111,0.363636,0.714286,0.389831,0.0,1.0
3,0.597222,0.527273,0.130952,0.644068,1.0,0.0
4,0.375000,0.327273,0.607143,0.338983,0.0,1.0
...,...,...,...,...,...,...
328,0.569444,0.636364,0.226190,0.745763,0.0,1.0
329,0.333333,0.185455,0.750000,0.203390,0.0,1.0
330,0.138889,0.276364,0.547619,0.355932,1.0,0.0
331,0.347222,0.476364,0.559524,0.440678,1.0,0.0
332,0.131944,0.218182,0.464286,0.152542,1.0,0.0

In [24]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()
penguins_y

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: object

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0,
       0, 1, 0], dtype=int8)

In [25]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
outputs = layers.Dense(3, activation='sigmoid')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [26]:
model.summary()

Model: "penguin_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 7)              │            49 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 5)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 3)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119 (476.00 B)

 Trainable params: 119 (476.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) for `plot_model` to work.

In [28]:
#the issue witht he code, nan fields in the data, need to drop them
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)
#shuffles the data and splits it into batches of 64, then trains the model for 100 epochs, using 10% of the data for validation
history = model.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs=100, validation_split=0.1)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=2)

Epoch 1/100

c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4448 - loss: 1.0950 - val_accuracy: 0.3824 - val_loss: 1.0995
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4448 - loss: 1.0869 - val_accuracy: 0.3824 - val_loss: 1.0954
Epoch 3/100
1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3438 - loss: 1.1079

c:\Users\2003n\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4448 - loss: 1.0818 - val_accuracy: 0.3824 - val_loss: 1.0919
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4448 - loss: 1.0773 - val_accuracy: 0.3824 - val_loss: 1.0880
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4448 - loss: 1.0734 - val_accuracy: 0.3824 - val_loss: 1.0831
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4448 - loss: 1.0693 - val_accuracy: 0.3824 - val_loss: 1.0795
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 1.0653 - val_accuracy: 0.3824 - val_loss: 1.0760
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 1.0612 - val_accuracy: 0.3824 - val_loss: 1.0725
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 1.0571 - val_accuracy: 0.3824 - val_loss: 1.0678
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 1.0527 - val_accuracy: 0.3824 - val_loss: 1.0629
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4448 - loss: 1.0478 - val_accuracy: 0.3824 - val_loss: 1.0574
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4448 - loss: 1.0409 - val_accuracy: 0.3824 - val_loss: 1.0510
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4448 - loss: 1.0340 - val_accuracy: 0.3824 - val_loss: 1.0448
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4448 - loss: 1.0275 - val_accuracy: 0.3824 - val_loss: 1.0384
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4448 - loss: 1.0204 - val_accuracy: 0.3824 - val_loss: 1.0348
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4448 - loss: 1.0137 - val_accuracy: 0.3824 - val_loss: 1.0283
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4448 - loss: 1.0069 - val_accuracy: 0.3824 - val_loss: 1.0207
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4448 - loss: 1.0002 - val_accuracy: 0.3824 - val_loss: 1.0133
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 0.9927 - val_accuracy: 0.3824 - val_loss: 1.0077
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 0.9853 - val_accuracy: 0.3824 - val_loss: 0.9994
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4448 - loss: 0.9782 - val_accuracy: 0.3824 - val_loss: 0.9920
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4448 - loss: 0.9704 - val_accuracy: 0.3824 - val_loss: 0.9853
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 0.9627 - val_accuracy: 0.3824 - val_loss: 0.9799
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4448 - loss: 0.9551 - val_accuracy: 0.3824 - val_loss: 0.9699
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 0.9475 - val_accuracy: 0.3824 - val_loss: 0.9621
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 0.9394 - val_accuracy: 0.3824 - val_loss: 0.9584
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4482 - loss: 0.9329 - val_accuracy: 0.3824 - val_loss: 0.9466
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4582 - loss: 0.9254 - val_accuracy: 0.3824 - val_loss: 0.9384
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4783 - loss: 0.9179 - val_accuracy: 0.4118 - val_loss: 0.9326
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4883 - loss: 0.9104 - val_accuracy: 0.4118 - val_loss: 0.9256
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5084 - loss: 0.9023 - val_accuracy: 0.5000 - val_loss: 0.9173
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5652 - loss: 0.8942 - val_accuracy: 0.5000 - val_loss: 0.9093
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5953 - loss: 0.8860 - val_accuracy: 0.5882 - val_loss: 0.8986
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6254 - loss: 0.8773 - val_accuracy: 0.5882 - val_loss: 0.8908
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6455 - loss: 0.8689 - val_accuracy: 0.5882 - val_loss: 0.8837
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6321 - loss: 0.8601 - val_accuracy: 0.6471 - val_loss: 0.8724
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6555 - loss: 0.8513 - val_accuracy: 0.6471 - val_loss: 0.8618
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6756 - loss: 0.8425 - val_accuracy: 0.6471 - val_loss: 0.8528
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6990 - loss: 0.8339 - val_accuracy: 0.6471 - val_loss: 0.8468
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6856 - loss: 0.8267 - val_accuracy: 0.6471 - val_loss: 0.8372
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7090 - loss: 0.8178 - val_accuracy: 0.7059 - val_loss: 0.8276
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7191 - loss: 0.8101 - val_accuracy: 0.7059 - val_loss: 0.8210
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7191 - loss: 0.8024 - val_accuracy: 0.7059 - val_loss: 0.8123
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7324 - loss: 0.7948 - val_accuracy: 0.7059 - val_loss: 0.8054
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7358 - loss: 0.7872 - val_accuracy: 0.7353 - val_loss: 0.7970
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7425 - loss: 0.7800 - val_accuracy: 0.7353 - val_loss: 0.7904
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7492 - loss: 0.7727 - val_accuracy: 0.7059 - val_loss: 0.7858
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7391 - loss: 0.7659 - val_accuracy: 0.7353 - val_loss: 0.7774
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7425 - loss: 0.7600 - val_accuracy: 0.7647 - val_loss: 0.7692
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7559 - loss: 0.7531 - val_accuracy: 0.7647 - val_loss: 0.7634
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7559 - loss: 0.7466 - val_accuracy: 0.7647 - val_loss: 0.7560
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7592 - loss: 0.7402 - val_accuracy: 0.7941 - val_loss: 0.7466
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7659 - loss: 0.7342 - val_accuracy: 0.7941 - val_loss: 0.7407
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7793 - loss: 0.7282 - val_accuracy: 0.7941 - val_loss: 0.7347
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7759 - loss: 0.7218 - val_accuracy: 0.7941 - val_loss: 0.7285
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7793 - loss: 0.7158 - val_accuracy: 0.7941 - val_loss: 0.7230
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7826 - loss: 0.7103 - val_accuracy: 0.7941 - val_loss: 0.7176
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7826 - loss: 0.7044 - val_accuracy: 0.7941 - val_loss: 0.7125
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7893 - loss: 0.6988 - val_accuracy: 0.7941 - val_loss: 0.7067
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7860 - loss: 0.6937 - val_accuracy: 0.7941 - val_loss: 0.7020
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7893 - loss: 0.6880 - val_accuracy: 0.7941 - val_loss: 0.6969
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7860 - loss: 0.6828 - val_accuracy: 0.7941 - val_loss: 0.6926
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7893 - loss: 0.6779 - val_accuracy: 0.7941 - val_loss: 0.6877
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7893 - loss: 0.6726 - val_accuracy: 0.7941 - val_loss: 0.6823
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7893 - loss: 0.6681 - val_accuracy: 0.7941 - val_loss: 0.6773
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7893 - loss: 0.6634 - val_accuracy: 0.7941 - val_loss: 0.6738
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7893 - loss: 0.6587 - val_accuracy: 0.7941 - val_loss: 0.6679
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7893 - loss: 0.6540 - val_accuracy: 0.7941 - val_loss: 0.6632
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7893 - loss: 0.6498 - val_accuracy: 0.7941 - val_loss: 0.6591
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.6465 - val_accuracy: 0.7941 - val_loss: 0.6548
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.6416 - val_accuracy: 0.7941 - val_loss: 0.6506
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7960 - loss: 0.6372 - val_accuracy: 0.7941 - val_loss: 0.6463
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7960 - loss: 0.6333 - val_accuracy: 0.7941 - val_loss: 0.6431
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7960 - loss: 0.6295 - val_accuracy: 0.7941 - val_loss: 0.6397
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.6263 - val_accuracy: 0.7941 - val_loss: 0.6363
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.6222 - val_accuracy: 0.7941 - val_loss: 0.6319
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.6186 - val_accuracy: 0.7941 - val_loss: 0.6282
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7960 - loss: 0.6152 - val_accuracy: 0.7941 - val_loss: 0.6249
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7960 - loss: 0.6126 - val_accuracy: 0.7941 - val_loss: 0.6217
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7960 - loss: 0.6087 - val_accuracy: 0.7941 - val_loss: 0.6183
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7960 - loss: 0.6048 - val_accuracy: 0.7941 - val_loss: 0.6158
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7960 - loss: 0.6015 - val_accuracy: 0.7941 - val_loss: 0.6118
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7960 - loss: 0.5982 - val_accuracy: 0.7941 - val_loss: 0.6080
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7960 - loss: 0.5949 - val_accuracy: 0.7941 - val_loss: 0.6067
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.5923 - val_accuracy: 0.7941 - val_loss: 0.6033
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7960 - loss: 0.5890 - val_accuracy: 0.7941 - val_loss: 0.6001
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7960 - loss: 0.5854 - val_accuracy: 0.7941 - val_loss: 0.5978
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7960 - loss: 0.5830 - val_accuracy: 0.7941 - val_loss: 0.5954
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.5804 - val_accuracy: 0.7941 - val_loss: 0.5921
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7960 - loss: 0.5767 - val_accuracy: 0.7941 - val_loss: 0.5888
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7960 - loss: 0.5742 - val_accuracy: 0.7941 - val_loss: 0.5869
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.5714 - val_accuracy: 0.7941 - val_loss: 0.5855
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7960 - loss: 0.5684 - val_accuracy: 0.7941 - val_loss: 0.5824
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.5656 - val_accuracy: 0.7941 - val_loss: 0.5798
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.5631 - val_accuracy: 0.7941 - val_loss: 0.5769
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.5604 - val_accuracy: 0.7941 - val_loss: 0.5740
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.5574 - val_accuracy: 0.7941 - val_loss: 0.5726
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7960 - loss: 0.5548 - val_accuracy: 0.7941 - val_loss: 0.5692
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7960 - loss: 0.5524 - val_accuracy: 0.7941 - val_loss: 0.5675
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.5497 - val_accuracy: 0.7941 - val_loss: 0.5641
11/11 - 0s - 3ms/step - accuracy: 0.7958 - loss: 0.5492

In [29]:
model_logit_false = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_false.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_false = model_logit_false.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 100, validation_split = 0.1)

scores = model_logit_false.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.7960 - loss: 0.5478 - val_accuracy: 0.7941 - val_loss: 0.5605
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.5423 - val_accuracy: 0.7941 - val_loss: 0.5572
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.5385 - val_accuracy: 0.7941 - val_loss: 0.5544
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7960 - loss: 0.5360 - val_accuracy: 0.7941 - val_loss: 0.5536
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.5342 - val_accuracy: 0.7941 - val_loss: 0.5509
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.5306 - val_accuracy: 0.7941 - val_loss: 0.5475
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7960 - loss: 0.5288 - val_accuracy: 0.7941 - val_loss: 0.5446
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7960 - loss: 0.5269 - val_accuracy: 0.7941 - val_loss: 0.5429
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7960 - loss: 0.5238 - val_accuracy: 0.7941 - val_loss: 0.5431
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7960 - loss: 0.5225 - val_accuracy: 0.7941 - val_loss: 0.5397
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.5193 - val_accuracy: 0.7941 - val_loss: 0.5371
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7960 - loss: 0.5183 - val_accuracy: 0.7941 - val_loss: 0.5348
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7993 - loss: 0.5162 - val_accuracy: 0.7941 - val_loss: 0.5336
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7993 - loss: 0.5129 - val_accuracy: 0.7941 - val_loss: 0.5317
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7993 - loss: 0.5108 - val_accuracy: 0.7941 - val_loss: 0.5296
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8060 - loss: 0.5095 - val_accuracy: 0.7941 - val_loss: 0.5275
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7993 - loss: 0.5064 - val_accuracy: 0.7941 - val_loss: 0.5253
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8094 - loss: 0.5043 - val_accuracy: 0.7941 - val_loss: 0.5228
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8094 - loss: 0.5020 - val_accuracy: 0.7941 - val_loss: 0.5199
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8127 - loss: 0.4998 - val_accuracy: 0.7941 - val_loss: 0.5202
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8227 - loss: 0.4979 - val_accuracy: 0.7941 - val_loss: 0.5180
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8261 - loss: 0.4958 - val_accuracy: 0.8235 - val_loss: 0.5138
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8227 - loss: 0.4929 - val_accuracy: 0.8235 - val_loss: 0.5126
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8328 - loss: 0.4916 - val_accuracy: 0.8235 - val_loss: 0.5096
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8328 - loss: 0.4887 - val_accuracy: 0.8235 - val_loss: 0.5083
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8328 - loss: 0.4872 - val_accuracy: 0.8235 - val_loss: 0.5051
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8361 - loss: 0.4841 - val_accuracy: 0.8529 - val_loss: 0.5031
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8395 - loss: 0.4818 - val_accuracy: 0.8529 - val_loss: 0.5015
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8528 - loss: 0.4798 - val_accuracy: 0.8529 - val_loss: 0.4998
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8395 - loss: 0.4774 - val_accuracy: 0.8529 - val_loss: 0.4960
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8428 - loss: 0.4753 - val_accuracy: 0.8529 - val_loss: 0.4964
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8528 - loss: 0.4736 - val_accuracy: 0.8529 - val_loss: 0.4934
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8528 - loss: 0.4702 - val_accuracy: 0.8529 - val_loss: 0.4893
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8662 - loss: 0.4681 - val_accuracy: 0.8529 - val_loss: 0.4901
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8629 - loss: 0.4660 - val_accuracy: 0.8529 - val_loss: 0.4874
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8629 - loss: 0.4638 - val_accuracy: 0.8824 - val_loss: 0.4812
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8696 - loss: 0.4613 - val_accuracy: 0.8824 - val_loss: 0.4784
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8729 - loss: 0.4595 - val_accuracy: 0.8824 - val_loss: 0.4758
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8763 - loss: 0.4572 - val_accuracy: 0.8824 - val_loss: 0.4754
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8729 - loss: 0.4541 - val_accuracy: 0.8824 - val_loss: 0.4735
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8763 - loss: 0.4529 - val_accuracy: 0.8824 - val_loss: 0.4706
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8930 - loss: 0.4495 - val_accuracy: 0.9118 - val_loss: 0.4671
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8896 - loss: 0.4475 - val_accuracy: 0.9118 - val_loss: 0.4638
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8963 - loss: 0.4452 - val_accuracy: 0.9118 - val_loss: 0.4649
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8997 - loss: 0.4425 - val_accuracy: 0.9118 - val_loss: 0.4589
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8997 - loss: 0.4404 - val_accuracy: 0.9118 - val_loss: 0.4559
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9097 - loss: 0.4381 - val_accuracy: 0.9118 - val_loss: 0.4546
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9130 - loss: 0.4365 - val_accuracy: 0.9412 - val_loss: 0.4533
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9097 - loss: 0.4337 - val_accuracy: 0.9412 - val_loss: 0.4512
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9197 - loss: 0.4318 - val_accuracy: 0.9412 - val_loss: 0.4492
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9231 - loss: 0.4289 - val_accuracy: 0.9412 - val_loss: 0.4456
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9197 - loss: 0.4270 - val_accuracy: 0.9706 - val_loss: 0.4425
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9331 - loss: 0.4243 - val_accuracy: 0.9706 - val_loss: 0.4407
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9231 - loss: 0.4219 - val_accuracy: 0.9706 - val_loss: 0.4368
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9298 - loss: 0.4193 - val_accuracy: 0.9706 - val_loss: 0.4337
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9164 - loss: 0.4176 - val_accuracy: 0.9706 - val_loss: 0.4333
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9264 - loss: 0.4149 - val_accuracy: 0.9706 - val_loss: 0.4327
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9431 - loss: 0.4128 - val_accuracy: 0.9706 - val_loss: 0.4281
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9331 - loss: 0.4102 - val_accuracy: 0.9706 - val_loss: 0.4248
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9197 - loss: 0.4084 - val_accuracy: 0.9706 - val_loss: 0.4254
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9431 - loss: 0.4051 - val_accuracy: 0.9706 - val_loss: 0.4203
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9398 - loss: 0.4026 - val_accuracy: 0.9706 - val_loss: 0.4180
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9431 - loss: 0.4005 - val_accuracy: 0.9706 - val_loss: 0.4147
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9331 - loss: 0.3984 - val_accuracy: 0.9706 - val_loss: 0.4139
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9431 - loss: 0.3953 - val_accuracy: 0.9706 - val_loss: 0.4109
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9398 - loss: 0.3936 - val_accuracy: 0.9706 - val_loss: 0.4081
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9431 - loss: 0.3911 - val_accuracy: 0.9706 - val_loss: 0.4051
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9365 - loss: 0.3894 - val_accuracy: 0.9706 - val_loss: 0.4036
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9431 - loss: 0.3863 - val_accuracy: 0.9706 - val_loss: 0.4035
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9431 - loss: 0.3840 - val_accuracy: 0.9706 - val_loss: 0.3988
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9465 - loss: 0.3821 - val_accuracy: 0.9706 - val_loss: 0.3959
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9431 - loss: 0.3798 - val_accuracy: 0.9706 - val_loss: 0.3924
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9431 - loss: 0.3773 - val_accuracy: 0.9706 - val_loss: 0.3902
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9465 - loss: 0.3751 - val_accuracy: 0.9706 - val_loss: 0.3881
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9498 - loss: 0.3728 - val_accuracy: 0.9706 - val_loss: 0.3871
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9498 - loss: 0.3702 - val_accuracy: 0.9706 - val_loss: 0.3844
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9465 - loss: 0.3684 - val_accuracy: 0.9706 - val_loss: 0.3807
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9431 - loss: 0.3667 - val_accuracy: 0.9706 - val_loss: 0.3796
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9465 - loss: 0.3641 - val_accuracy: 0.9706 - val_loss: 0.3758
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9498 - loss: 0.3614 - val_accuracy: 0.9706 - val_loss: 0.3741
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9465 - loss: 0.3589 - val_accuracy: 0.9706 - val_loss: 0.3725
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9532 - loss: 0.3569 - val_accuracy: 0.9706 - val_loss: 0.3684
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9498 - loss: 0.3549 - val_accuracy: 0.9706 - val_loss: 0.3678
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9498 - loss: 0.3527 - val_accuracy: 0.9706 - val_loss: 0.3666
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9532 - loss: 0.3500 - val_accuracy: 0.9706 - val_loss: 0.3627
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9532 - loss: 0.3487 - val_accuracy: 0.9706 - val_loss: 0.3600
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9532 - loss: 0.3465 - val_accuracy: 0.9706 - val_loss: 0.3575
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9532 - loss: 0.3437 - val_accuracy: 0.9706 - val_loss: 0.3560
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9532 - loss: 0.3419 - val_accuracy: 0.9706 - val_loss: 0.3529
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9532 - loss: 0.3396 - val_accuracy: 0.9706 - val_loss: 0.3501
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9565 - loss: 0.3381 - val_accuracy: 0.9706 - val_loss: 0.3480
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9532 - loss: 0.3355 - val_accuracy: 0.9706 - val_loss: 0.3451
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9565 - loss: 0.3331 - val_accuracy: 0.9706 - val_loss: 0.3439
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9565 - loss: 0.3316 - val_accuracy: 0.9706 - val_loss: 0.3433
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9532 - loss: 0.3287 - val_accuracy: 0.9706 - val_loss: 0.3396
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9565 - loss: 0.3267 - val_accuracy: 0.9706 - val_loss: 0.3384
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9565 - loss: 0.3254 - val_accuracy: 0.9706 - val_loss: 0.3350
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9565 - loss: 0.3228 - val_accuracy: 0.9706 - val_loss: 0.3320
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9565 - loss: 0.3203 - val_accuracy: 0.9706 - val_loss: 0.3319
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9565 - loss: 0.3181 - val_accuracy: 0.9706 - val_loss: 0.3285
11/11 - 0s - 2ms/step - accuracy: 0.9580 - loss: 0.3176

In [30]:
model_logit_false.predict(scaled_penguins_x)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

array([[9.80567694e-01, 6.21935427e-01, 9.22420993e-04],
       [3.54071826e-01, 5.50172448e-01, 6.40702367e-01],
       [9.80249584e-01, 7.05797970e-01, 8.76440376e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.82978702e-01, 6.98900819e-01, 6.86033804e-04],
       [5.63631415e-01, 7.37313092e-01, 2.80333996e-01],
       [7.26973653e-01, 7.77897358e-01, 1.03313170e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.20116305e-01, 7.37994611e-01, 1.00263515e-02],
       [9.99186039e-01, 6.29222512e-01, 4.19582557e-06],
       [8.19650829e-01, 6.81378782e-01, 4.80554923e-02],
       [9.82487559e-01, 6.01321578e-01, 7.81365670e-04],
       [4.79087144e-01, 6.70303941e-01, 4.14911538e-01],
       [9.82690275e-01, 6.02506042e-01, 7.66790239e-04],
       [9.89969492e-01, 5.96094131e-01, 3.05919180e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.89981294e-01, 5.89362025e-01, 3.04512534e-04],
       [4.32848811e-01, 6.39736891e-01, 4.90610272e-01],
       [9.60337460e-01, 7.22988248e-01, 2.91134138e-03],
       [9.78547871e-01, 6.99512243e-01, 1.02856453e-03],
       [3.60490650e-01, 5.59448004e-01, 6.27862990e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.82315898e-01, 6.12501383e-01, 7.87097553e-04],
       [9.74553704e-01, 6.24812782e-01, 1.46576599e-03],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [5.94883204e-01, 7.56701469e-01, 2.38926768e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [6.93451643e-01, 7.85145283e-01, 1.30603254e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.95610213e-01, 6.08187437e-01, 5.56537986e-01],
       [9.80134368e-01, 7.09684551e-01, 8.79520376e-04],
       [9.68514621e-01, 6.18926466e-01, 2.13908963e-03],
       [5.03960669e-01, 6.94202304e-01, 3.70996058e-01],
       [6.73238218e-01, 7.84321606e-01, 1.50580361e-01],
       [3.89564723e-01, 6.00041747e-01, 5.68890691e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.91727173e-01, 5.83491206e-01, 2.21929979e-04],
       [9.89259541e-01, 5.94958901e-01, 3.43613036e-04],
       [9.95520949e-01, 5.93440115e-01, 7.85779775e-05],
       [9.88754392e-01, 5.90741932e-01, 3.71526374e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.89094973e-01, 6.84129834e-01, 3.24525608e-04],
       [9.81005609e-01, 5.99114299e-01, 9.00644867e-04],
       [6.30331874e-01, 7.79720962e-01, 1.95395008e-01],
       [9.92748082e-01, 6.79721892e-01, 1.62099910e-04],
       [9.97172296e-01, 6.58456326e-01, 3.34112847e-05],
       [5.88565588e-01, 7.55718291e-01, 2.45429352e-01],
       [9.88787055e-01, 5.80763042e-01, 3.71195027e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.98014092e-01, 6.43350780e-01, 1.88810009e-05],
       [9.73378003e-01, 6.21856451e-01, 1.57000928e-03],
       [3.15948337e-01, 4.92818922e-01, 7.14544952e-01],
       [9.61222649e-01, 6.42535210e-01, 2.98375823e-03],
       [9.93686736e-01, 6.83768809e-01, 1.25858132e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [7.83968866e-01, 6.89180970e-01, 6.85091540e-02],
       [5.69209158e-01, 7.39939034e-01, 2.73189336e-01],
       [6.26398087e-01, 7.77364850e-01, 1.99904740e-01],
       [9.88371015e-01, 5.96593380e-01, 3.91408772e-04],
       [9.98810112e-01, 6.36536479e-01, 7.92686569e-06],
       [3.81019473e-01, 5.88353992e-01, 5.86320639e-01],
       [9.75334823e-01, 6.09547019e-01, 1.41048210e-03],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.79262292e-01, 6.08322144e-01, 1.03927648e-03],
       [8.93257201e-01, 6.61273360e-01, 1.80378295e-02],
       [9.92518365e-01, 5.80668092e-01, 1.87113925e-04],
       [9.94583845e-01, 6.70465708e-01, 1.00090998e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [5.54557562e-01, 7.30424404e-01, 2.93655902e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.96192694e-01, 6.63503706e-01, 5.52212405e-05],
       [9.97183919e-01, 6.58868849e-01, 3.30743023e-05],
       [9.93979752e-01, 6.70737505e-01, 1.19757889e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.78148103e-01, 6.25234842e-01, 1.12158549e-03],
       [9.93203998e-01, 6.77222252e-01, 1.45688275e-04],
       [3.16794932e-01, 4.94133413e-01, 7.12961316e-01],
       [9.74480867e-01, 6.12838387e-01, 1.47319667e-03],
       [6.28903270e-01, 7.75628328e-01, 1.98654637e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.96586740e-01, 6.63294315e-01, 4.57108727e-05],
       [3.52378815e-01, 5.47707260e-01, 6.44073546e-01],
       [3.34621221e-01, 5.21387219e-01, 6.78971291e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [6.37264431e-01, 7.80845881e-01, 1.89071044e-01],
       [9.69905138e-01, 7.15851307e-01, 1.80289522e-03],
       [9.77492511e-01, 7.05489516e-01, 1.10555184e-03],
       [9.85462785e-01, 6.97113574e-01, 5.20617759e-04],
       [9.96141672e-01, 5.91049790e-01, 6.11907089e-05],
       [9.93952215e-01, 6.79696977e-01, 1.18260061e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.65466022e-01, 7.19759226e-01, 2.29207287e-03],
       [9.96500611e-01, 6.68209434e-01, 4.70966079e-05],
       [9.53022242e-01, 6.43197298e-01, 4.17536264e-03],
       [6.25851154e-01, 7.76436090e-01, 2.00841144e-01],
       [5.29180646e-01, 7.15005577e-01, 3.29959214e-01],
       [9.78804648e-01, 6.06474280e-01, 1.07725570e-03],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.89138603e-01, 5.90519309e-01, 3.49324197e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.88469779e-01, 5.96581638e-01, 3.85656051e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.89032328e-01, 6.03068471e-01, 3.54912656e-04],
       [5.43276846e-01, 7.23614693e-01, 3.09548408e-01],
       [8.71653557e-01, 6.72218680e-01, 2.57516503e-02],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.70713139e-01, 6.21118724e-01, 1.86221278e-03],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [8.63377810e-01, 6.72870040e-01, 2.87072044e-02],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.95339751e-01, 6.64852381e-01, 7.81919734e-05],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [6.19494140e-01, 7.72443175e-01, 2.08355010e-01],
       [9.95374978e-01, 6.65019035e-01, 7.70323168e-05],
       [9.93831933e-01, 6.67903543e-01, 1.26228071e-04],
       [4.34751451e-01, 6.42817736e-01, 4.86368090e-01],
       [9.97187674e-01, 5.82777441e-01, 3.60700360e-05],
       [9.92237449e-01, 6.82365537e-01, 1.80330564e-04],
       [9.63560939e-01, 7.22225487e-01, 2.50891107e-03],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.82086480e-01, 6.11583710e-01, 8.10873113e-04],
       [9.97442126e-01, 6.57675862e-01, 2.81867833e-05],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.86987650e-01, 5.85854471e-01, 4.76065092e-04],
       [9.97249365e-01, 5.95277369e-01, 3.45854678e-05],
       [9.94512260e-01, 5.93077660e-01, 1.10640081e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [8.93688142e-01, 7.52073050e-01, 1.66842882e-02],
       [6.91676497e-01, 7.83290088e-01, 1.32993981e-01],
       [9.86117601e-01, 5.89415193e-01, 5.29951765e-04],
       [9.70939875e-01, 7.14004278e-01, 1.69747241e-03],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.94560599e-01, 5.78399897e-01, 1.09609915e-04],
       [3.53111237e-01, 5.48774719e-01, 6.42615974e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [5.45259953e-01, 7.11420596e-01, 3.14502597e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.60757291e-01, 5.59830904e-01, 6.27327681e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.79536414e-01, 7.00829625e-01, 9.44646483e-04],
       [9.62231040e-01, 7.27758706e-01, 2.64219102e-03],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.25654238e-01, 5.07780194e-01, 6.96216583e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.88001347e-01, 5.90601325e-01, 4.15249408e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.36400121e-01, 5.24061620e-01, 6.75517559e-01],
       [9.69925761e-01, 7.15164483e-01, 1.80141116e-03],
       [6.16086900e-01, 7.70921469e-01, 2.12119997e-01],
       [5.16232193e-01, 6.91567183e-01, 3.58427823e-01],
       [5.14915705e-01, 7.09101975e-01, 3.49440545e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [8.92085969e-01, 6.62179053e-01, 1.84391346e-02],
       [9.96218145e-01, 6.63683534e-01, 5.43473798e-05],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [5.52494884e-01, 7.28042722e-01, 2.97193050e-01],
       [9.57425714e-01, 6.30677164e-01, 3.54786334e-03],
       [4.70924556e-01, 6.63611531e-01, 4.28866595e-01],
       [4.49476212e-01, 6.51310742e-01, 4.62778419e-01],
       [9.93389845e-01, 6.78007305e-01, 1.38420670e-04],
       [9.92037117e-01, 5.87518215e-01, 2.07750723e-04],
       [9.72392917e-01, 6.12888813e-01, 1.70159375e-03],
       [9.69163358e-01, 6.22403979e-01, 2.02968065e-03],
       [4.93463129e-01, 6.80011451e-01, 3.91854286e-01],
       [9.79772687e-01, 7.09431767e-01, 9.07672453e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [4.89627391e-01, 6.75911069e-01, 3.98878127e-01],
       [9.87662733e-01, 6.90080523e-01, 3.98131844e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.59309340e-01, 6.32218599e-01, 3.26742115e-03],
       [6.14831686e-01, 7.69430280e-01, 2.14000449e-01],
       [9.91630435e-01, 6.79990053e-01, 2.07417412e-04],
       [6.35287523e-01, 7.82524288e-01, 1.89872876e-01],
       [9.53570426e-01, 7.25395620e-01, 3.81905236e-03],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [8.11484694e-01, 6.85272515e-01, 5.28286919e-02],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.86666203e-01, 7.03029156e-01, 4.43224766e-04],
       [9.94577289e-01, 5.93763590e-01, 1.08410044e-04],
       [9.92574930e-01, 6.78119779e-01, 1.69463587e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.80931103e-01, 5.99244833e-01, 9.06456436e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.91744280e-01, 6.85663819e-01, 1.99065413e-04],
       [6.44667149e-01, 7.11494565e-01, 1.87573746e-01],
       [9.89142895e-01, 6.87084198e-01, 3.19851883e-04],
       [9.83253002e-01, 7.06439495e-01, 6.53390132e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [8.16203475e-01, 7.62346148e-01, 4.70434241e-02],
       [9.93325233e-01, 6.73483014e-01, 1.42340752e-04],
       [9.66538548e-01, 7.19497681e-01, 2.14938261e-03],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.93494511e-01, 5.80220222e-01, 1.48107953e-04],
       [9.97902393e-01, 6.44243956e-01, 2.07391786e-05],
       [4.22368258e-01, 6.32586360e-01, 5.08153677e-01],
       [9.93538857e-01, 5.87649345e-01, 1.45996426e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.96054649e-01, 6.61305606e-01, 5.91262251e-05],
       [6.47868037e-01, 7.83887148e-01, 1.77273601e-01],
       [7.01867580e-01, 7.74281263e-01, 1.26184016e-01],
       [4.63797241e-01, 6.60974503e-01, 4.39198166e-01],
       [8.68794203e-01, 6.72453165e-01, 2.67498624e-02],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [7.82246470e-01, 6.91694558e-01, 6.93478212e-02],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.55193818e-01, 7.30446100e-01, 3.56574659e-03],
       [3.15651149e-01, 4.92357045e-01, 7.15100169e-01],
       [9.83015180e-01, 6.15957022e-01, 7.38973089e-04],
       [9.83922064e-01, 6.97205663e-01, 6.21674000e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.91001427e-01, 6.84501529e-01, 2.32738297e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.78396058e-01, 7.10092902e-01, 1.01545616e-03],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.51094931e-01, 5.45832634e-01, 6.46625400e-01],
       [9.59317982e-01, 6.28451586e-01, 3.27699818e-03],
       [5.27675390e-01, 6.96436882e-01, 3.42587084e-01],
       [3.23338836e-01, 5.04232883e-01, 7.00622320e-01],
       [5.62549829e-01, 7.35507727e-01, 2.82471031e-01],
       [9.61834311e-01, 6.32350683e-01, 2.92499317e-03],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.96911645e-01, 6.61206722e-01, 3.85984786e-05],
       [9.52889025e-01, 6.35685802e-01, 4.22871299e-03],
       [9.51468647e-01, 6.50440216e-01, 4.38221730e-03],
       [3.37496459e-01, 5.25705695e-01, 6.73383951e-01],
       [3.27993810e-01, 5.11350513e-01, 6.91744626e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [8.86456490e-01, 6.67510152e-01, 2.00598687e-02],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.73685384e-01, 6.15625560e-01, 1.56129489e-03],
       [9.85898316e-01, 5.99173784e-01, 5.44407812e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.85205233e-01, 6.87965751e-01, 5.48179727e-04],
       [9.78039622e-01, 6.12925172e-01, 1.14141230e-03],
       [9.97947454e-01, 6.52451456e-01, 1.94954264e-05],
       [9.95957077e-01, 5.70121050e-01, 6.67204004e-05],
       [9.70869303e-01, 7.25021124e-01, 1.67077314e-03],
       [3.17236811e-01, 4.94818777e-01, 7.12133527e-01],
       [9.92726564e-01, 6.81047320e-01, 1.62502911e-04],
       [5.23298919e-01, 6.97470844e-01, 3.46908569e-01],
       [8.13376606e-01, 7.00849295e-01, 5.05136512e-02],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [5.66542149e-01, 7.38194466e-01, 2.76872784e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [5.04553914e-01, 6.97254181e-01, 3.68465155e-01],
       [3.15719396e-01, 4.92463171e-01, 7.14972734e-01],
       [5.69984794e-01, 7.22472847e-01, 2.80581176e-01],
       [6.30194902e-01, 7.79820323e-01, 1.95459947e-01],
       [5.85214496e-01, 7.50711977e-01, 2.51396239e-01],
       [3.17171842e-01, 4.94718015e-01, 7.12255299e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.93323505e-01, 6.83923244e-01, 1.38609277e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.60754812e-01, 7.31478572e-01, 2.81366333e-03],
       [9.95974183e-01, 6.64006352e-01, 6.06337089e-05],
       [9.41807151e-01, 6.39522076e-01, 6.11158786e-03],
       [9.86062884e-01, 6.92418694e-01, 4.88859368e-04],
       [9.98586416e-01, 6.38975143e-01, 1.05976533e-05],
       [3.15236658e-01, 4.91712511e-01, 7.15873957e-01],
       [9.94853973e-01, 6.73418880e-01, 9.10702729e-05],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.85515118e-01, 6.97323322e-01, 5.18885790e-04],
       [9.92755890e-01, 6.02262020e-01, 1.76088273e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.96558309e-01, 5.79084635e-01, 5.07211735e-05],
       [9.89756703e-01, 5.92765570e-01, 3.17383528e-04],
       [4.61608231e-01, 6.58181190e-01, 4.43579882e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [4.28970575e-01, 6.35495782e-01, 4.98041838e-01],
       [8.71853769e-01, 6.69505715e-01, 2.53836177e-02],
       [5.54155231e-01, 7.29287267e-01, 2.94733405e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.91728365e-01, 5.93092322e-01, 2.21067894e-04],
       [9.64732707e-01, 6.25283897e-01, 2.55897897e-03],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [5.33534408e-01, 7.16797411e-01, 3.24112296e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.34195554e-01, 5.20745993e-01, 6.79796219e-01],
       [9.92375314e-01, 6.02175236e-01, 1.91992309e-04],
       [9.95698571e-01, 5.90572774e-01, 7.34851710e-05],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.92917359e-01, 6.74404263e-01, 1.57467060e-04],
       [3.15317422e-01, 4.91838127e-01, 7.15723276e-01],
       [6.57832146e-01, 7.88088918e-01, 1.65004179e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [4.74968553e-01, 6.67399585e-01, 4.21655566e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [4.39229906e-01, 6.42228007e-01, 4.81069267e-01],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.89106357e-01, 5.93703747e-01, 3.52123112e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.94981050e-01, 6.67043805e-01, 8.82718523e-05],
       [9.92224336e-01, 6.79613709e-01, 1.83261538e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.75915730e-01, 7.10510790e-01, 1.23383745e-03],
       [3.55089396e-01, 5.51650405e-01, 6.38672948e-01],
       [9.94387627e-01, 5.74300289e-01, 1.15725517e-04],
       [3.14589858e-01, 4.90705937e-01, 7.17079818e-01],
       [9.98438716e-01, 6.41234159e-01, 1.25292072e-05],
       [9.25572395e-01, 6.48006558e-01, 9.43916012e-03],
       [4.30899501e-01, 6.36108518e-01, 4.95233268e-01],
       [9.87666070e-01, 6.08556509e-01, 4.30472894e-04]], dtype=float32)

In [31]:
penguins['species']

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: object

In [32]:
penguins_y

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0,
       0, 1, 0], dtype=int8)